services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bakery_web_app
    container_name: bakery_app
    restart: unless-stopped
    working_dir: /var/www/bakery_web_app
    volumes:
      - .:/var/www/bakery_web_app
    networks:
      - laravel
    depends_on:
      - mysql
    ports:
      - "8000:80"

  mysql:
    image: mysql:8.0
    container_name: mysql_sahabat_group
    restart: always
    environment:
      MYSQL_DATABASE: sahabat_group_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sahabat_group
      MYSQL_PASSWORD: sahabatgroup
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - laravel

volumes:
  mysql-data:


networks:
  laravel:
    driver: bridge
